version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "autoweave/core-team"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "prettier*"
      production-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "@types/*"
          - "eslint*"
          - "jest*"
          - "prettier*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    reviewers:
      - "autoweave/devops-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
    reviewers:
      - "autoweave/devops-team"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/packages/memory"
    schedule:
      interval: "weekly"
    reviewers:
      - "autoweave/devops-team"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
    reviewers:
      - "autoweave/devops-team"
    labels:
      - "dependencies"
      - "docker"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/packages/memory"
    schedule:
      interval: "weekly"
    reviewers:
      - "autoweave/memory-team"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"