version: '3.8'

services:
  # Redis for session management
  redis:
    image: redis:7-alpine
    container_name: autoweave-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # GraphQL Gateway
  gateway:
    build: .
    container_name: autoweave-gateway
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - agents-subgraph
      - memory-subgraph
      - queue-subgraph
      - plugins-subgraph
      - observability-subgraph
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-jwt-secret-change-in-production
      - JWT_REFRESH_SECRET=your-jwt-refresh-secret-change-in-production
      - AGENTS_SUBGRAPH_URL=http://agents-subgraph:4001/graphql
      - MEMORY_SUBGRAPH_URL=http://memory-subgraph:4002/graphql
      - QUEUE_SUBGRAPH_URL=http://queue-subgraph:4003/graphql
      - PLUGINS_SUBGRAPH_URL=http://plugins-subgraph:4004/graphql
      - OBSERVABILITY_SUBGRAPH_URL=http://observability-subgraph:4005/graphql
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8080
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Agents Subgraph
  agents-subgraph:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        SUBGRAPH_NAME: agents
        SUBGRAPH_PORT: 4001
    container_name: autoweave-agents-subgraph
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - PORT=4001
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Memory Subgraph
  memory-subgraph:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        SUBGRAPH_NAME: memory
        SUBGRAPH_PORT: 4002
    container_name: autoweave-memory-subgraph
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
      - PORT=4002
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Queue Subgraph
  queue-subgraph:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        SUBGRAPH_NAME: queue
        SUBGRAPH_PORT: 4003
    container_name: autoweave-queue-subgraph
    ports:
      - "4003:4003"
    environment:
      - NODE_ENV=production
      - PORT=4003
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4003/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Plugins Subgraph
  plugins-subgraph:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        SUBGRAPH_NAME: plugins
        SUBGRAPH_PORT: 4004
    container_name: autoweave-plugins-subgraph
    ports:
      - "4004:4004"
    environment:
      - NODE_ENV=production
      - PORT=4004
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Observability Subgraph
  observability-subgraph:
    build:
      context: .
      dockerfile: Dockerfile.subgraph
      args:
        SUBGRAPH_NAME: observability
        SUBGRAPH_PORT: 4005
    container_name: autoweave-observability-subgraph
    ports:
      - "4005:4005"
    environment:
      - NODE_ENV=production
      - PORT=4005
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  default:
    driver: bridge