apiVersion: v2
name: autoweave
description: The Self-Weaving Agent Orchestrator - Complete Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - agents
  - ai
  - orchestration
  - kagent
home: https://github.com/autoweave/autoweave
sources:
  - https://github.com/autoweave/autoweave
maintainers:
  - name: AutoWeave Team
    email: team@autoweave.dev
icon: https://raw.githubusercontent.com/autoweave/autoweave/main/assets/logo.png

dependencies:
  - name: redis
    version: "19.0.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    
  - name: postgresql
    version: "14.2.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    
  - name: prometheus
    version: "25.11.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
    
  - name: grafana
    version: "7.3.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/redis
    - url: https://artifacthub.io/packages/helm/prometheus-community/prometheus