apiVersion: v2
name: autoweave
description: Production-Ready AI Agent Orchestration Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.25.0"

keywords:
  - kubernetes
  - agents
  - ai
  - orchestration
  - automation
  - microservices
  - observability
  - production

home: https://github.com/autoweave/autoweave
sources:
  - https://github.com/autoweave/autoweave

maintainers:
  - name: AutoWeave Team
    email: maintainers@autoweave.dev
    url: https://github.com/autoweave/autoweave

icon: https://raw.githubusercontent.com/autoweave/autoweave/main/assets/logo.png

dependencies:
  # Core Infrastructure
  - name: redis
    version: "~18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
    tags:
      - storage
      - cache
    
  - name: postgresql
    version: "~13.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    tags:
      - storage
      - database
  
  # Observability Stack
  - name: tempo
    version: "~1.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: observability.tempo.enabled
    tags:
      - observability
      - tracing
      
  - name: loki
    version: "~5.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: observability.loki.enabled
    tags:
      - observability
      - logging
      
  - name: grafana
    version: "~7.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: observability.grafana.enabled
    tags:
      - observability
      - monitoring
      
  - name: prometheus
    version: "~25.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: observability.prometheus.enabled
    tags:
      - observability
      - metrics
      
  # Message Queue
  - name: rabbitmq
    version: "~12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: messageQueue.rabbitmq.enabled
    tags:
      - messaging
      - queue
      
  # Service Mesh (Optional)
  - name: istio-base
    version: "~1.20.x"
    repository: "https://istio-release.storage.googleapis.com/charts"
    condition: serviceMesh.istio.enabled
    tags:
      - networking
      - security

annotations:
  # Artifact Hub metadata
  artifacthub.io/license: MIT
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/signKey: |
    fingerprint: 1234567890ABCDEF1234567890ABCDEF12345678
    url: https://github.com/autoweave/autoweave/releases/download/v1.0.0/autoweave.asc
  artifacthub.io/crds: |
    - kind: Agent
      version: v1
      name: agents.autoweave.io
      displayName: AutoWeave Agent
      description: Custom resource for managing AI agents
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/bitnami/redis
    - url: https://artifacthub.io/packages/helm/bitnami/postgresql
    - url: https://artifacthub.io/packages/helm/prometheus-community/prometheus
    - url: https://artifacthub.io/packages/helm/grafana/grafana
    - url: https://artifacthub.io/packages/helm/grafana/loki
  artifacthub.io/changes: |
    - kind: added
      description: Production-ready Helm chart with security hardening
    - kind: added
      description: Multi-architecture container support
    - kind: added
      description: Comprehensive observability stack integration
    - kind: added
      description: Advanced security policies and network policies
    - kind: improved
      description: Resource management and auto-scaling capabilities
  
  # Kubernetes specific annotations
  meta.helm.sh/release-name: autoweave
  meta.helm.sh/release-namespace: autoweave-system
  
  # Security annotations
  seccomp.security.alpha.kubernetes.io/pod: runtime/default
  container.apparmor.security.beta.kubernetes.io/autoweave: runtime/default
  
  # Custom AutoWeave annotations
  autoweave.io/version: "1.0.0"
  autoweave.io/build-date: "2025-07-14"
  autoweave.io/security-scan: "passed"
  autoweave.io/sbom-available: "true"
  autoweave.io/signed: "cosign"